title: Kris Carta's personal blog
description: Personal Site and Blog
author: Kris Carta
author-tagline: Hi, I'm Kris
github: https://github.com/kcarta
about: I'm a software manager and developer, and this is my space for exploring thoughts on *everything* to do with modern (agile) software delivery, from management to technology

google_analytics: UA-45886163-5

enableTags: true
tagarray: []

social:
    - icon: fa-linkedin
      link: "https://www.linkedin.com/in/kriscarta"
    - icon: fa-github
      link: "https://github.com/kcarta"

#share:
#  twitter_username: github.io
#  fb_appid: 1749788565247320

urls:
    - text: About
      url: /about/
    - text: XML Feed
      url: /feed.xml

url: "https://www.kriscarta.com"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
plugins:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']

# The URL for the staticman API bridge endpoint
# You will want to modify some of the values:
#  ${github-username}: the username of the account with which you publish your blog
#  ${blog-repo}: the name of your blog repository in github
#  master: this the branch out of which your blog is published, often master or gh-pages
#  ${bridge_app_name}: the name you chose in Heroku for your bridge API
#  comments: the so-called property, this defines the key in staticman.yml where the configuration is found
#
# for me, this line reads:
# https://staticman-travisdownsio.herokuapp.com/v2/entry/travisdowns/travisdowns.github.io/master/comments
staticman_url: https://kcarta-github-pages-comments.herokuapp.com/v2/entry/kcarta/kcarta.github.io/master/comments

reCaptcha:
  siteKey: 6LcsRsgZAAAAAGrkx0RrnolQOE76v8GHzqJ97Y2g
  secret: JgWbalMqV2hpbbYh5OmhndMUYYNmUiGxIHnjDft7nIEOpC/ITDU5jXe3gstcLot5e4r1X7pk/6ZSfYuy3pjMwpXZWn0d9hn/0SPilXe9CThuf6qZuYqAMJP/+SskV7eJ9kQCVTkC62zc7zga4UrvUDjhzm8261TJavxl7grXFK+aDTag5vbD8dy0/NdJilmXP4YZsOXlyVIpP8sZvImQGw7Epvl9CnO6jGq3sLykxLrvzArYWwaJrGK26aSXeX3JQaYSnq6kKFxJtkNaRejtw4FreFYMyf+6LBlLhNf0vuOON1yQ3xUtVmPcGvq6OreIOSo+DjZ5p3V3+Z8Qjj3OiIqf2QcCb5z9yiT7P+S5Gkf5Wy2kNgXHL+LlkQABbR67/YYWmQkc+w8NGDtyY/pKfJ1RH9qFwoIny2vndAPT/pQ069HcmZXKZiMErJ4pVasH9yoOULN3iS8IBuex7VD+7QcLVxPh/8SOQpKMRvdwhJGBNsTe7aDNlN5y+39F/G2iebul0p3/RyljUi6Lo8KmaN5tMYwtisF2wlpC0SLttGawNhvRKPR/SbsA5AjV0CJ3VnxWC9dDYvyxLHs1BNVKjjNeJDzcRvK+0AI1hPW0qodqsBNiWqZJPXlqoyh3Smt30g8udmxSiNaB7XEvsqIk7BUrPinn2YXiX4wealo+cdM=